-- ═══════════════════════════════════════════════════════════════════════════════
-- 0028 · THE WRITE PRIVILEGES THE ELIGIBILITY LAYER ACTUALLY NEEDS
-- ═══════════════════════════════════════════════════════════════════════════════
--
-- This migration exists because 0027 granted the RIGHT rule to the WRONG list of
-- columns, and neither the unit suite nor a code review could see it.
--
-- WHAT HAPPENED
--   0027 granted `firm_api` column-level INSERT on the four new tables, listing
--   the columns that carry meaning: the licence number, the dates, the outcome,
--   the evidence. It withheld `id`, `created_at`, `updated_at` and
--   `evaluated_at` on the reasoning that the database should own them — they are
--   identity and audit metadata, and a client that can set an evaluation time can
--   backdate evidence.
--
--   The reasoning was sound and the result was a production HTTP 500:
--
--     PostgreSQL requires a column privilege for EVERY column NAMED in the
--     statement, including one that has a default. Omitting a column from the
--     INSERT list is free; naming it and supplying a value demands the grant.
--
--   The server names these columns deliberately. `FirmRepo` generates ids in
--   TypeScript (`newId()`) because SQLite's mirror has no `gen_random_uuid()` and
--   the repository layer's whole job is to behave identically on both engines, and
--   it writes timestamps explicitly because every other write path in this codebase
--   does. So the grant list and the statement disagreed, the refusal was a
--   permission error rather than a constraint violation, and it surfaced as
--   `internal_error` on the FIRST request that refrained a matter grant to a
--   suspended lawyer — the exact path the phase was built for.
--
--   SQLite could not catch it: one role owns the file, column privileges do not
--   exist there, and all 346 tests passed while the feature was broken in
--   production. This is the twelfth instance of the same class of defect, and the
--   first that a check now precedes: `scripts/verify/schema-parity.ts` measures
--   every statement the server issues against the privileges it holds, and fails
--   when they disagree.
--
-- THE DECISION TAKEN HERE
--   Grant the columns, rather than rewrite the server to stop naming them.
--   Consistency is the reason: `audit_events.occurred_at` is server-written and
--   granted, `invoices.created_at` is server-written and granted, and inventing a
--   second convention for four columns would mean the next person has to know
--   which tables follow which rule. The single-writer server is trusted by
--   construction — RLS confines `firm_api` to one tenant and the only way to reach
--   it is the API.
--
--   What is deliberately NOT granted is listed at the end, because the withheld
--   columns are the ones that carry a decision.
--
-- Grantees: firm_api only. The four tables are firm diligence surfaces and the
-- portal role holds nothing on them (asserted live by scripts/verify/eligibility-live.mjs).
-- ═══════════════════════════════════════════════════════════════════════════════

begin;

-- ── professional_licences ────────────────────────────────────────────────────
-- `id`: generated by the server (`newId()`), which is what makes the SQLite mirror
--   work without a UUID function. `verified_at`/`created_at`/`updated_at`: named
--   explicitly by `upsertLicence`.
grant insert (id, created_at, updated_at, verified_at)
  on public.professional_licences to firm_api;

-- ── prior_office ─────────────────────────────────────────────────────────────
-- Append-only: there is no UPDATE grant and there will not be one. A prior
-- appointment that happened is a fact about a career; correcting it means
-- recording what was corrected, not editing the row.
grant insert (id, created_at, updated_at)
  on public.prior_office to firm_api;

-- ── eligibility_checks ───────────────────────────────────────────────────────
-- `evaluated_at` is the timestamp of the decision, written by the gate. It is the
-- one column here whose grant is genuinely arguable: a compromised server could
-- backdate a check. The alternative — dropping it from the INSERT and letting the
-- default apply — would make this table the only one in the schema that does not
-- take its timestamp from the application, and the divergence would be invisible
-- in every test. Consistency with `audit_events` won; the risk it accepts is the
-- risk the rest of the audit trail already accepts.
grant insert (evaluated_at)
  on public.eligibility_checks to firm_api;

-- ── tenant_relationships ─────────────────────────────────────────────────────
-- Nothing to add: `declared_at` has a default and the server does not name it.
-- Left ungranted on purpose — a declared relationship is dated by the declaration,
-- and the row is the firm's assertion rather than a record of an event the server
-- observed.
--
-- Note the asymmetry with `eligibility_checks` above, which is real and is the
-- point of writing this down: the two tables look alike and take opposite
-- decisions, because one records what the SYSTEM observed and the other records
-- what a MEMBER asserted.

-- ── deliberately NOT granted ─────────────────────────────────────────────────
--   professional_licences.evidence_document_id
--     The support for a licence claim is a document, and the path that attaches
--     one does not exist yet. The column is in the schema and unreachable: a
--     licence cannot be recorded as verified-with-proof until the server can say
--     which document, so leaving it ungranted keeps the API honest about a
--     capability it does not have. Granting it "for later" is how a projection
--     starts leaking fields nobody intended to expose.
--   prior_office / professional_licences DELETE
--     Nothing is deleted. A revoked licence is a `status`, and a prior appointment
--     that ended is an `ended_on`. A row that can vanish makes the register
--     un-auditable at exactly the moment it matters — after a dispute.
--   tenant_relationships UPDATE
--     A declared relationship that can be edited is not a declaration. A change is
--     a new declaration.

-- ── verify ───────────────────────────────────────────────────────────────────
do $$
declare
  missing text;
begin
  /*
    The check is written as the thing that failed, not as the thing that should
    exist: it lists columns the server names that remain ungranted. A migration
    that forgot one would otherwise apply cleanly and 500 later, which is the
    entire history of this defect class.
  */
  select string_agg(t.table_name || '.' || t.column_name || ' (' || t.priv || ')', ', ')
    into missing
    from (values
      ('professional_licences', 'id', 'INSERT'),
      ('professional_licences', 'verified_at', 'INSERT'),
      ('professional_licences', 'created_at', 'INSERT'),
      ('professional_licences', 'updated_at', 'INSERT'),
      ('professional_licences', 'issued_at', 'UPDATE'),
      ('professional_licences', 'expires_at', 'UPDATE'),
      ('professional_licences', 'status', 'UPDATE'),
      ('professional_licences', 'status_effective_from', 'UPDATE'),
      ('professional_licences', 'status_reference', 'UPDATE'),
      ('professional_licences', 'verified_by_membership_id', 'UPDATE'),
      ('professional_licences', 'verified_at', 'UPDATE'),
      ('professional_licences', 'updated_at', 'UPDATE'),
      ('prior_office', 'id', 'INSERT'),
      ('prior_office', 'created_at', 'INSERT'),
      ('prior_office', 'updated_at', 'INSERT'),
      ('eligibility_checks', 'evaluated_at', 'INSERT')
    ) as t(table_name, column_name, priv)
   where not exists (
     select 1 from information_schema.column_privileges cp
      where cp.table_schema = 'public'
        and cp.table_name = t.table_name
        and cp.column_name = t.column_name
        and cp.grantee = 'firm_api'
        and cp.privilege_type = t.priv
   );

  if missing is not null then
    raise exception 'firm_api still cannot write: %', missing;
  end if;
end $$;

commit;
