-- ═══════════════════════════════════════════════════════════════════════════════
-- 0055 · the privilege ring
-- ═══════════════════════════════════════════════════════════════════════════════
--
-- GENERATED FILE — do not edit by hand. Regenerate with:
--     node scripts/generate-audit-vocabulary.mjs
--
-- WHAT HAPPENS IF THIS FILE IS NOT APPLIED. Not a crash. The write fails the CHECK and
-- `tryWrite` swallows it with a console warning, so an issued invoice is not recorded
-- as issued, a client's money is received and no row says so, and a discount beyond
-- authority leaves no trace — while the product behaves perfectly. That is the failure
-- mode this codebase keeps meeting: silent in one direction, catastrophic in the other.
--
-- THE LIST IS GENERATED FROM THE UNION, IN ORDER, NOT TYPED. 150 actions.
-- ═══════════════════════════════════════════════════════════════════════════════

alter table public.audit_events drop constraint if exists audit_events_action_check;

alter table public.audit_events add constraint audit_events_action_check
  check (action in (
    'LOGIN',
    'LOGIN_FAILED',
    'LOGOUT',
    'LOGOUT_ALL_OTHERS',
    'SESSION_EXPIRED',
    'SESSION_REVOKED',
    'ACCOUNT_LOCKED',
    'RATE_CARD_RECORDED',
    'RATE_LIMITED',
    'PASSWORD_RESET_REQUESTED',
    'PASSWORD_RESET_COMPLETED',
    'PASSWORD_CHANGED',
    'EMAIL_VERIFICATION_SENT',
    'EMAIL_VERIFIED',
    'INVITATION_CREATED',
    'INVITATION_ACCEPTED',
    'INVITATION_EXPIRED',
    'INVITATION_REVOKED',
    'MFA_ENROLLMENT_STARTED',
    'MFA_ENABLED',
    'MFA_DISABLED',
    'MFA_VERIFIED',
    'MFA_FAILED',
    'DEVICE_TRUSTED',
    'DEVICE_UNTRUSTED',
    'DOCUMENT_VIEWED',
    'DOCUMENT_DOWNLOADED',
    'DOCUMENT_UPLOADED',
    'DOCUMENT_UPLOAD_REJECTED',
    'SIGNED_URL_ISSUED',
    'DOCUMENT_ACCESS_DENIED',
    'INVOICE_VIEWED',
    'PAYMENT_STARTED',
    'PAYMENT_COMPLETED',
    'PAYMENT_FAILED',
    'RECEIPT_VIEWED',
    'WEBHOOK_RECEIVED',
    'WEBHOOK_SIGNATURE_INVALID',
    'MESSAGE_SENT',
    'MESSAGE_READ',
    'APPOINTMENT_REQUESTED',
    'APPOINTMENT_CANCELLED',
    'PROFILE_UPDATED',
    'PREFERENCES_UPDATED',
    'NOTIFICATION_READ',
    'PRIVACY_REQUEST_SUBMITTED',
    'CONSENT_RECORDED',
    'AUTHZ_DENIED',
    'TENANT_ISOLATION_VIOLATION',
    'CLIENT_ISOLATION_VIOLATION',
    'INTERNAL_RESOURCE_ACCESS_ATTEMPT',
    'FIELD_TAMPER_ATTEMPT',
    'MUTATION_DENIED',
    'FIRM_LOGIN',
    'FIRM_LOGIN_FAILED',
    'FIRM_LOGOUT',
    'FIRM_SESSION_REVOKED',
    'FIRM_MFA_VERIFIED',
    'FIRM_MFA_FAILED',
    'PERMISSION_DENIED',
    'MATTER_SCOPE_DENIED',
    'CEILING_EXCEEDED',
    'ROLE_GRANTED',
    'ROLE_REVOKED',
    'MATTER_ACCESS_GRANTED',
    'MATTER_ACCESS_REVOKED',
    'MATTER_RESTRICTED',
    'MATTER_UNRESTRICTED',
    'ESCALATION_ATTEMPT',
    'ADMIN_MUTATION',
    'PARTY_CREATED',
    'PARTY_UPDATED',
    'PARTY_MERGED',
    'PARTY_ALIAS_ADDED',
    'PARTY_AFFILIATION_RECORDED',
    'MATTER_PARTY_ADDED',
    'MATTER_PARTY_UPDATED',
    'MATTER_STATUS_CHANGED',
    'CONFLICT_CHECK_RUN',
    'CONFLICT_HIT',
    'CONFLICT_DISPOSITION_RECORDED',
    'CONFLICT_CLEARED',
    'CONFLICT_DECLINED',
    'CONFLICT_WAIVED',
    'MATTER_VIEWED',
    'LICENCE_RECORDED',
    'LICENCE_STATUS_CHANGED',
    'LICENCE_VERIFIED',
    'PRIOR_OFFICE_RECORDED',
    'TENANT_RELATIONSHIP_DECLARED',
    'ELIGIBILITY_EVALUATED',
    'ELIGIBILITY_DENIED',
    'MULTI_FIRM_AFFILIATION_DENIED',
    'FISCAL_IDENTITY_RECORDED',
    'FISCAL_DEVICE_RECORDED',
    'INVOICE_ISSUED',
    'INVOICE_SUBMITTED',
    'INVOICE_CLEARED',
    'INVOICE_REPORTED',
    'INVOICE_REJECTED',
    'CREDIT_NOTE_ISSUED',
    'TRUST_RECEIPT_RECORDED',
    'TRUST_APPLIED_TO_INVOICE',
    'TRUST_DISBURSEMENT_RECORDED',
    'TRUST_REFUND_PAID',
    'TRUST_LEDGER_FROZEN',
    'TRUST_DISCREPANCY_FOUND',
    'LEDGER_RECONCILED',
    'TIME_ENTRY_RECORDED',
    'TIME_ENTRY_ADJUSTED',
    'TIME_WRITTEN_OFF',
    'EXPENSE_RECORDED',
    'EXPENSE_APPROVED',
    'EXPENSE_REJECTED',
    'BILLING_TERMS_SET',
    'ENGAGEMENT_LETTER_RECORDED',
    'ENGAGEMENT_LETTER_SIGNED',
    'ENGAGEMENT_GATE_DENIED',
    'WRITE_OFF_APPROVED',
    'DISCOUNT_APPLIED',
    'CDD_RECORDED',
    'CDD_UPDATED',
    'CDD_COMPLETED',
    'CDD_UNABLE_TO_COMPLETE',
    'CDD_REVIEW_SCHEDULED',
    'CDD_GATE_DENIED',
    'BENEFICIAL_OWNER_RECORDED',
    'BENEFICIAL_OWNER_VERIFIED',
    'SCREENING_RUN',
    'SCREENING_MATCH_FOUND',
    'SCREENING_MATCH_DISPOSITIONED',
    'SCREENING_FAILED',
    'RISK_ASSESSED',
    'RISK_COUNTRY_RECORDED',
    'STR_PREPARED',
    'STR_REVIEWED',
    'STR_FILED',
    'STR_RESPONSE_RECORDED',
    'JUDGMENT_RECORDED',
    'JUDGMENT_AMENDED',
    'JUDGMENT_SERVICE_RECORDED',
    'APPEAL_PERIOD_COMPUTED',
    'APPEAL_FILED',
    'EXECUTION_GATE_DENIED',
    'EXECUTION_STAYED',
    'EXECUTION_STAY_LIFTED',
    'COURT_CALENDAR_RECORDED',
    'COURT_CALENDAR_REMOVED',
    'PRIVILEGED_READ',
    'PRIVILEGE_RELEASED'
  ));

-- ─────────────────────────────────────────────────────────────────────────────
-- SELF-VERIFICATION. The constraint is asserted to exist, to admit every declared
-- action, and to have been built from this list rather than from a stale one.
-- ─────────────────────────────────────────────────────────────────────────────
do $$
declare
  missing text;
  admitted integer;
begin
  if not exists (
    select 1 from pg_constraint where conname = 'audit_events_action_check'
  ) then
    raise exception '0055: audit_events_action_check was not created';
  end if;

  select count(*) into admitted
    from pg_constraint
   where conname = 'audit_events_action_check'
     and pg_get_constraintdef(oid) like '%''LOGIN''%';
  if admitted = 0 then
    raise exception '0055: the constraint does not look like an action list';
  end if;

  select string_agg(a, ', ') into missing
    from unnest(array[
    'LOGIN',
    'LOGIN_FAILED',
    'LOGOUT',
    'LOGOUT_ALL_OTHERS',
    'SESSION_EXPIRED',
    'SESSION_REVOKED',
    'ACCOUNT_LOCKED',
    'RATE_CARD_RECORDED',
    'RATE_LIMITED',
    'PASSWORD_RESET_REQUESTED',
    'PASSWORD_RESET_COMPLETED',
    'PASSWORD_CHANGED',
    'EMAIL_VERIFICATION_SENT',
    'EMAIL_VERIFIED',
    'INVITATION_CREATED',
    'INVITATION_ACCEPTED',
    'INVITATION_EXPIRED',
    'INVITATION_REVOKED',
    'MFA_ENROLLMENT_STARTED',
    'MFA_ENABLED',
    'MFA_DISABLED',
    'MFA_VERIFIED',
    'MFA_FAILED',
    'DEVICE_TRUSTED',
    'DEVICE_UNTRUSTED',
    'DOCUMENT_VIEWED',
    'DOCUMENT_DOWNLOADED',
    'DOCUMENT_UPLOADED',
    'DOCUMENT_UPLOAD_REJECTED',
    'SIGNED_URL_ISSUED',
    'DOCUMENT_ACCESS_DENIED',
    'INVOICE_VIEWED',
    'PAYMENT_STARTED',
    'PAYMENT_COMPLETED',
    'PAYMENT_FAILED',
    'RECEIPT_VIEWED',
    'WEBHOOK_RECEIVED',
    'WEBHOOK_SIGNATURE_INVALID',
    'MESSAGE_SENT',
    'MESSAGE_READ',
    'APPOINTMENT_REQUESTED',
    'APPOINTMENT_CANCELLED',
    'PROFILE_UPDATED',
    'PREFERENCES_UPDATED',
    'NOTIFICATION_READ',
    'PRIVACY_REQUEST_SUBMITTED',
    'CONSENT_RECORDED',
    'AUTHZ_DENIED',
    'TENANT_ISOLATION_VIOLATION',
    'CLIENT_ISOLATION_VIOLATION',
    'INTERNAL_RESOURCE_ACCESS_ATTEMPT',
    'FIELD_TAMPER_ATTEMPT',
    'MUTATION_DENIED',
    'FIRM_LOGIN',
    'FIRM_LOGIN_FAILED',
    'FIRM_LOGOUT',
    'FIRM_SESSION_REVOKED',
    'FIRM_MFA_VERIFIED',
    'FIRM_MFA_FAILED',
    'PERMISSION_DENIED',
    'MATTER_SCOPE_DENIED',
    'CEILING_EXCEEDED',
    'ROLE_GRANTED',
    'ROLE_REVOKED',
    'MATTER_ACCESS_GRANTED',
    'MATTER_ACCESS_REVOKED',
    'MATTER_RESTRICTED',
    'MATTER_UNRESTRICTED',
    'ESCALATION_ATTEMPT',
    'ADMIN_MUTATION',
    'PARTY_CREATED',
    'PARTY_UPDATED',
    'PARTY_MERGED',
    'PARTY_ALIAS_ADDED',
    'PARTY_AFFILIATION_RECORDED',
    'MATTER_PARTY_ADDED',
    'MATTER_PARTY_UPDATED',
    'MATTER_STATUS_CHANGED',
    'CONFLICT_CHECK_RUN',
    'CONFLICT_HIT',
    'CONFLICT_DISPOSITION_RECORDED',
    'CONFLICT_CLEARED',
    'CONFLICT_DECLINED',
    'CONFLICT_WAIVED',
    'MATTER_VIEWED',
    'LICENCE_RECORDED',
    'LICENCE_STATUS_CHANGED',
    'LICENCE_VERIFIED',
    'PRIOR_OFFICE_RECORDED',
    'TENANT_RELATIONSHIP_DECLARED',
    'ELIGIBILITY_EVALUATED',
    'ELIGIBILITY_DENIED',
    'MULTI_FIRM_AFFILIATION_DENIED',
    'FISCAL_IDENTITY_RECORDED',
    'FISCAL_DEVICE_RECORDED',
    'INVOICE_ISSUED',
    'INVOICE_SUBMITTED',
    'INVOICE_CLEARED',
    'INVOICE_REPORTED',
    'INVOICE_REJECTED',
    'CREDIT_NOTE_ISSUED',
    'TRUST_RECEIPT_RECORDED',
    'TRUST_APPLIED_TO_INVOICE',
    'TRUST_DISBURSEMENT_RECORDED',
    'TRUST_REFUND_PAID',
    'TRUST_LEDGER_FROZEN',
    'TRUST_DISCREPANCY_FOUND',
    'LEDGER_RECONCILED',
    'TIME_ENTRY_RECORDED',
    'TIME_ENTRY_ADJUSTED',
    'TIME_WRITTEN_OFF',
    'EXPENSE_RECORDED',
    'EXPENSE_APPROVED',
    'EXPENSE_REJECTED',
    'BILLING_TERMS_SET',
    'ENGAGEMENT_LETTER_RECORDED',
    'ENGAGEMENT_LETTER_SIGNED',
    'ENGAGEMENT_GATE_DENIED',
    'WRITE_OFF_APPROVED',
    'DISCOUNT_APPLIED',
    'CDD_RECORDED',
    'CDD_UPDATED',
    'CDD_COMPLETED',
    'CDD_UNABLE_TO_COMPLETE',
    'CDD_REVIEW_SCHEDULED',
    'CDD_GATE_DENIED',
    'BENEFICIAL_OWNER_RECORDED',
    'BENEFICIAL_OWNER_VERIFIED',
    'SCREENING_RUN',
    'SCREENING_MATCH_FOUND',
    'SCREENING_MATCH_DISPOSITIONED',
    'SCREENING_FAILED',
    'RISK_ASSESSED',
    'RISK_COUNTRY_RECORDED',
    'STR_PREPARED',
    'STR_REVIEWED',
    'STR_FILED',
    'STR_RESPONSE_RECORDED',
    'JUDGMENT_RECORDED',
    'JUDGMENT_AMENDED',
    'JUDGMENT_SERVICE_RECORDED',
    'APPEAL_PERIOD_COMPUTED',
    'APPEAL_FILED',
    'EXECUTION_GATE_DENIED',
    'EXECUTION_STAYED',
    'EXECUTION_STAY_LIFTED',
    'COURT_CALENDAR_RECORDED',
    'COURT_CALENDAR_REMOVED',
    'PRIVILEGED_READ',
    'PRIVILEGE_RELEASED'
    ]) a
   where not exists (
     select 1 from pg_constraint
      where conname = 'audit_events_action_check'
        and pg_get_constraintdef(oid) like '%''' || a || '''%'
   );
  if missing is not null then
    raise exception '0055: declared but not admitted: %', missing;
  end if;

  raise notice '0055: audit vocabulary at 150 actions — verified against the declared union';
end $$;
